
apiVersion: apps/v1

kind: Deployment

metadata:

      name: go-app-deployment

spec:

  replicas: 3

  selector:

    matchLabels:

      app: go-app

  strategy:

    type: Recreate

  template:

    metadata:

      labels:

        app: go-app

    spec:

      containers:

      - name: go-app

        image: mawan1122/kube-zodiakapp:v6

        envFrom:

          - secretRef:

              name: mysql-secret

        ports:

           - containerPort: 8081
---

apiVersion: v1

kind: Service

metadata:

  name: go-app-service

spec:

  selector:

    app: go-app

  ports:

    - port: 8080

      targetPort: 8081
 
---

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: example-ingress

  annotations:

      nginx.ingress.kubernetes.io/rewrite-target: /
spec:

  rules:

    - host: rogerdev.mawan.info

      http:

        paths:

          - path: /

            pathType: Prefix

            backend:

              service:

                name: go-app-service
                port:

                  number: 8080
          