
apiVersion: apps/v1

kind: Deployment

metadata:

      name: rogerdev-blogspot-frontend-deployment

spec:

  replicas: 3

  selector:

    matchLabels:

      app: rogerdev-blogspot-frontend

  strategy:

    type: Recreate

  template:

    metadata:

      labels:

        app: rogerdev-blogspot-frontend

    spec:

      containers:

      - name: rogerdev-blogspot-frontend

        image: mawan1122/rogerdev-blogspot-frontend:latest

        envFrom:

          - secretRef:

              name: rogerdev-blogspot-frontend-secret

        ports:

           - containerPort: 8082
---

apiVersion: v1

kind: Service

metadata:

  name: rogerdev-blogspot-frontend-service

spec:

  selector:

    app: rogerdev-blogspot-frontend

  ports:

    - port: 8083

      targetPort: 8082
 
---

apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:

  name: rogerdev-blogspot-frontend-ingress

  annotations:

      nginx.ingress.kubernetes.io/rewrite-target: /
spec:

  rules:

    - host: rogerdev.mawan.info

      http:

        paths:

          - path: /

            pathType: Prefix

            backend:

              service:

                name: rogerdev-blogspot-frontend-service
                port:

                  number: 8083
          