apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:   # We dont need to worry about converting to base64
  MYSQL_USER: mawan
  MYSQL_PASSWORD: adol1122
  MYSQL_DATABASE: kube-zodiakapp
  MYSQL_ROOT_PASSWORD: adol1122

  DB_USERNAME: mawan
  APP_PORT: "8081"
  DB_ADDRESS: mysql-service.default.svc.cluster.local
  DB_DRIVER: mysql
  API_SECRET: 98hbun98h 
  DB_USER: mawan
  DB_PASSWORD: adol1122
  DB_NAME: kube-zodiakapp
  DB_PORT: "8082"