name: Deploy
on: 
  push:
    branches:
      - "main"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: mawan1122/rogerdev-blogspot-frontend:latest
    
    - name: checkout
      uses: actions/checkout@master
